<?php/*
 * m_login.php - sysmond web interface
 *
 * Copyright (C) 2012 - Sotiris Karagiorgis
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */?>


<?php

$host = host;
$user = username;
$pass = password;
$db_name = db_name;
$tbl_name1 = md5sums_safe;
$tbl_name2 = date_md5sums_safe;
$tbl_name3 = md5sums_unsafe;
$tbl_name4 = services_safe;
$tbl_name5 = services_unsafe;
$tbl_name6 = lsof;
$tbl_name7 = diff_md5;
$tbl_name8 = diff_ser;
$tbl_name9 = lsof_temp;
$tbl_name10 = ss_temp;
$tbl_name11 = ss_ports_temp;
$tbl_name12 = ss_http_temp;
$tbl_name13 = net_synrec_temp;
$tbl_name14 = net_ip_temp;
$tbl_name15 = net_ipcnt_temp;


?> 
