<?php/*
 * other_info.php - sysmond web interface
 *
 * Copyright (C) 2012 - Sotiris Karagiorgis
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */?>


<?php

$filename = '/var/run/sysmond.pid';
$filename2 = '/home/sotos/Downloads/src/sysmond/comm.dat';
$remote_socket = "unix:///var/run/sysmond.sock";
$snd_msg = "sixxt";
$snd_msg1 = "seven";
$snd_msg2 = "eight";
$snd_msg3 = "ninee";
$snd_msg4 = "tennn";
$snd_msg5 = "eleve";
$snd_msg6 = "twelv";
$snd_msgkill = "killt";

?>
